TRUE = 'true'
FALSE = 'false'
UNBOUNDED = 'UNBOUNDED'

INIT = 'INIT'
CHECKED = 'CHECKED'
POSITIVE = 'POSITIVE'
NEGATE = 'NEGATE'

RESULT = 'RESULT'
SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'

OPERATORS = ["<=>", "=>", "&", "|"]
#DELIMITER = '<=> => & |'
