lab1: lab1.cpp Graph.cpp Graph.h BFS.cpp BFS.h IterativeDeepeningSearch.cpp IterativeDeepeningSearch.h Astar.cpp Astar.h
	g++ -std=c++11 -g lab1.cpp Graph.cpp BFS.cpp IterativeDeepeningSearch.cpp Astar.cpp -o lab1
clean:
	rm -f lab1 *~